services:
  db:
    image: mysql:8.4
    ports:
      - ${MYSQL_PORT}:3306
    container_name: card_game-mysql
    volumes:
      - ./mysql/volumes:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file: .env

